version: '3.8'

services:
  runbook-service:
    build:
      context: ./Errors_table
      dockerfile: Dockerfile
    volumes:
      - ./Errors_table/Errors.json:/app/mongo_data.json
    ports:
      - "8000:8000"